import {
  Activity,
  ArrowRight,
  BarChart3,
  Bell,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  ClipboardList,
  Filter,
  Folder,
  Gift,
  Globe,
  Home,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  List,
  Loader2,
  LogOut,
  MapPin,
  Package,
  Palette,
  Pencil,
  Plus,
  Search,
  Settings,
  SlidersHorizontal,
  Sun,
  Tag,
  Trash2,
  Truck,
  User,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

const iconRegistry: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-right": ArrowRight,
  "bar-chart-3": BarChart3,
  bell: Bell,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-help": CircleHelp,
  "clipboard-list": ClipboardList,
  filter: Filter,
  folder: Folder,
  gift: Gift,
  globe: Globe,
  home: Home,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  list: List,
  "loader-2": Loader2,
  "log-out": LogOut,
  "map-pin": MapPin,
  package: Package,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  search: Search,
  settings: Settings,
  "sliders-horizontal": SlidersHorizontal,
  sun: Sun,
  tag: Tag,
  "trash-2": Trash2,
  truck: Truck,
  user: User,
  users: Users,
  x: X,
};

export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (!name) {
    return CircleHelp;
  }
  const icon = iconRegistry[name];
  if (!icon && process.env.NODE_ENV === "development") {
    console.warn(`[icon-registry] Unknown icon name "${name}", falling back to CircleHelp`);
  }
  return icon ?? CircleHelp;
}
